import {
  BadgeDollarSign,
  Bell,
  BookOpen,
  BookOpenCheck,
  Building2,
  ChartNoAxesColumnIncreasing,
  ChartPie,
  ClipboardCheck,
  ClipboardList,
  CreditCard,
  GraduationCap,
  LayoutDashboard,
  LayoutTemplate,
  ReceiptText,
  Settings,
  TicketPercent,
  Trophy,
  UserCog,
  UserPlus,
  UserRoundPlus,
  Users,
  UsersRound,
  WalletCards,
} from 'lucide-react';

/** Single source of truth for sidebar icons so every dashboard stays visually consistent. */
const NAV_ICONS = {
  overview: LayoutDashboard,
  requests: UserPlus,
  groups: UsersRound,
  subjects: BookOpen,
  students: GraduationCap,
  quizzes: ClipboardCheck,
  assignments: ClipboardList,
  assistants: UserCog,
  results: ChartNoAxesColumnIncreasing,
  reports: ChartPie,
  payments: WalletCards,
  paymentPlans: BadgeDollarSign,
  promoCodes: TicketPercent,
  paymentHistory: ReceiptText,
  platformSubscription: CreditCard,
  settings: Settings,
  myCourses: BookOpenCheck,
  joinGroup: UserRoundPlus,
  leaderboard: Trophy,
  selectAcademy: Building2,
  children: Users,
  notifications: Bell,
  tenants: Building2,
  subscriptions: CreditCard,
  cms: LayoutTemplate,
};

export default NAV_ICONS;
